### ISSUE TITLE
missing CMakeLists.txt file?

### ISSUE THREAD

**Issue by mpeaton** [JanosGit/Schrammel_OJD#31]
CMake Error at CMakeLists.txt:37 (add_subdirectory):
  The source directory

    ./Schrammel_OJD/Ext/JUCE

  does not contain a CMakeLists.txt file.

**Comment by JanosGit** [comment]
Is Ext/JUCE an empty folder? If so, you probably missed to checkout submodules. How did you clone the repository?

**Comment by mpeaton** [comment]
oh, *headsmack*.  Sorry hasty issue.  Thanks.
