### ISSUE TITLE
Building on linux fails

### ISSUE THREAD

**Issue by buscon** [JanosGit/Schrammel_OJD#43]
I am trying to build it on Linux Mint and I get the following error:
$ cmake -DCMAKE_BUILD_TYPE=Release -B build
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:39 (add_subdirectory):
  The source directory

    /home/marcello/Documents/Softwares/schrammel_ojd/Ext/JUCE

  does not contain a CMakeLists.txt file.

CMake Error at BinaryResources/CMakeLists.txt:24 (juce_add_binary_data):
  Unknown CMake command "juce_add_binary_data".

-- Configuring incomplete, errors occurred!
See also "/home/marcello/Documents/Softwares/schrammel_ojd/build/CMakeFiles/CMakeOutput.log".

How can it be fixed?

Thanks

**Comment by JanosGit** [comment]
All the directories in `Ext` are git submodules which need to be initialized first. The error message makes me assume that the `JUCE` subdirectory is empty which could be the case if you didn't initialize the submodules after cloning. Could this be the case?

**Comment by buscon** [comment]
> All the directories in `Ext` are git submodules which need to be initialized first. The error message makes me assume that the `JUCE` subdirectory is empty which could be the case if you didn't initialize the submodules after cloning. Could this be the case?

yes, that must be the case. how can I initialize the submodules?
I did  a
`git submodule init`
but I still get the same error.

**Comment by JanosGit** [comment]
Did you actually clone the repository using git or did you download it as zip from the GitHub website? `git submodule init` should only work if you cloned it with git in the first place, which is highly recommended. In case you cloned the project with git, does `git submodule init` return any output? What is the output of `git status`?

**Comment by buscon** [comment]
> Did you actually clone the repository using git or did you download it as zip from the GitHub website? `git submodule init` should only work if you cloned it with git in the first place, which is highly recommended. In case you cloned the project with git, does `git submodule init` return any output? What is the output of `git status`?

I did clone the github repository.
Here is the output of the submodule:
$ git submodule init
Submodule 'Ext/JBPluginBase' (https://github.com/JanosGit/PluginBase.git) registered for path 'Ext/JBPluginBase'
Submodule 'Ext/JUCE' (https://github.com/WeAreROLI/JUCE.git) registered for path 'Ext/JUCE'
Submodule 'Ext/Resvg4JUCE' (https://github.com/JanosGit/Resvg4JUCE.git) registered for path 'Ext/Resvg4JUCE'

Here is the output of the git status:

$ git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	build/

nothing added to commit but untracked files present (use "git add" to track)

**Comment by JanosGit** [comment]
Okay, this looks like the submodules are initialized properly. Did you also execute `git submodule update` afterwards to actually fetch the referenced submodule commits?

**Comment by buscon** [comment]
ok, good point, I did not do a `gut submodule update`. Now I did but I get another error:
`$ cmake -DCMAKE_BUILD_TYPE=Release -B build
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'alsa'
--   Found alsa, version 1.2.6.1
-- Checking for module 'freetype2'
--   Found freetype2, version 24.1.18
-- Checking for module 'libcurl'
--   Found libcurl, version 7.81.0
-- Checking for modules 'webkit2gtk-4.0;gtk+-x11-3.0'
--   Found webkit2gtk-4.0, version 2.38.5
--   Found gtk+-x11-3.0, version 3.24.33
-- Configuring juceaide
-- Building juceaide
-- Exporting juceaide
CMake Error at Ext/JBPluginBase/CMakeLists.txt:3 (add_subdirectory):
  The source directory

    /home/marcello/Documents/Softwares/schrammel_ojd/Ext/JBPluginBase/Ext/json

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
See also "/home/marcello/Documents/Softwares/schrammel_ojd/build/CMakeFiles/CMakeOutput.log".
`

**Comment by JanosGit** [comment]
Ah yes, there is a submodule inside the submodule. Just go to `schrammel_ojd/Ext/JBPluginBase` and do the same submodule init and update procedure from there.

Generally, you can simplify the whole process by just calling `git submodule update --init --recursive` once which will then recursively initialize and update all submodules in a repo that you just cloned.

**Comment by buscon** [comment]
I started from scratch and yes, cmake works now:
`
Schrammel_OJD $ cmake -DCMAKE_BUILD_TYPE=Release -B build
-- Checking for module 'freetype2'
--   Found freetype2, version 24.1.18
-- Checking for module 'libcurl'
--   Found libcurl, version 7.81.0
-- Checking for modules 'webkit2gtk-4.0;gtk+-x11-3.0'
--   Found webkit2gtk-4.0, version 2.38.5
--   Found gtk+-x11-3.0, version 3.24.33
-- Configuring juceaide
-- Building juceaide

-- Exporting juceaide
-- Using the single-header code from /home/marcello/Software/Schrammel_OJD/Ext/JBPluginBase/Ext/json/single_include/
-- Configuring done
-- Generating done
`

But after that, when I try to run make in the build directory, I get the following error:
`
Schrammel_OJD/build $ make -j8
[  2%] Generating juce_binarydata_EmbeddedBinaryData/JuceLibraryCode/BinaryData1.cpp, juce_binarydata_EmbeddedBinaryData/JuceLibraryCode/BinaryData2.cpp, juce_binarydata_EmbeddedBinaryData/JuceLibraryCode/BinaryData3.cpp, juce_binarydata_EmbeddedBinaryData/JuceLibraryCode/BinaryData4.cpp, juce_binarydata_EmbeddedBinaryData/JuceLibraryCode/BinaryData5.cpp, juce_binarydata_EmbeddedBinaryData/JuceLibraryCode/BinaryData6.cpp, juce_binarydata_EmbeddedBinaryData/JuceLibraryCode/BinaryData7.cpp, juce_binarydata_EmbeddedBinaryData/JuceLibraryCode/BinaryData8.cpp, juce_binarydata_EmbeddedBinaryData/JuceLibraryCode/BinaryData9.cpp, juce_binarydata_EmbeddedBinaryData/JuceLibraryCode/BinaryData10.cpp, juce_binarydata_EmbeddedBinaryData/JuceLibraryCode/BinaryData11.cpp, juce_binarydata_EmbeddedBinaryData/JuceLibraryCode/BinaryData12.cpp, juce_binarydata_EmbeddedBinaryData/JuceLibraryCode/BinaryData13.cpp, juce_binarydata_EmbeddedBinaryData/JuceLibraryCode/BinaryData14.cpp, juce_binarydata_EmbeddedBinaryData/JuceLibraryCode/BinaryData.h
/bin/sh: 1: cargo: not found
make[2]: *** [Ext/Resvg4JUCE/CMakeFiles/resvg_cargo_build.dir/build.make:70: Ext/Resvg4JUCE/CMakeFiles/resvg_cargo_build] Error 127
make[1]: *** [CMakeFiles/Makefile2:1139: Ext/Resvg4JUCE/CMakeFiles/resvg_cargo_build.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
-- Updated gitVersion.cpp
[  2%] Built target jb_create_git_version-OJD-VST3
[  4%] Building CXX object BinaryResources/CMakeFiles/EmbeddedBinaryData.dir/juce_binarydata_EmbeddedBinaryData/JuceLibraryCode/BinaryData1.cpp.o
[  6%] Building CXX object BinaryResources/CMakeFiles/EmbeddedBinaryData.dir/juce_binarydata_EmbeddedBinaryData/JuceLibraryCode/BinaryData4.cpp.o
[  8%] Building CXX object BinaryResources/CMakeFiles/EmbeddedBinaryData.dir/juce_binarydata_EmbeddedBinaryData/JuceLibraryCode/BinaryData3.cpp.o
[ 10%] Building CXX object BinaryResources/CMakeFiles/EmbeddedBinaryData.dir/juce_binarydata_EmbeddedBinaryData/JuceLibraryCode/BinaryData5.cpp.o
[ 12%] Building CXX object BinaryResources/CMakeFiles/EmbeddedBinaryData.dir/juce_binarydata_EmbeddedBinaryData/JuceLibraryCode/BinaryData7.cpp.o
[ 14%] Building CXX object BinaryResources/CMakeFiles/EmbeddedBinaryData.dir/juce_binarydata_EmbeddedBinaryData/JuceLibraryCode/BinaryData2.cpp.o
[ 16%] Building CXX object BinaryResources/CMakeFiles/EmbeddedBinaryData.dir/juce_binarydata_EmbeddedBinaryData/JuceLibraryCode/BinaryData6.cpp.o
[ 18%] Building CXX object BinaryResources/CMakeFiles/EmbeddedBinaryData.dir/juce_binarydata_EmbeddedBinaryData/JuceLibraryCode/BinaryData8.cpp.o
[ 20%] Building CXX object BinaryResources/CMakeFiles/EmbeddedBinaryData.dir/juce_binarydata_EmbeddedBinaryData/JuceLibraryCode/BinaryData10.cpp.o
[ 22%] Building CXX object BinaryResources/CMakeFiles/EmbeddedBinaryData.dir/juce_binarydata_EmbeddedBinaryData/JuceLibraryCode/BinaryData12.cpp.o
[ 24%] Building CXX object BinaryResources/CMakeFiles/EmbeddedBinaryData.dir/juce_binarydata_EmbeddedBinaryData/JuceLibraryCode/BinaryData9.cpp.o
[ 26%] Building CXX object BinaryResources/CMakeFiles/EmbeddedBinaryData.dir/juce_binarydata_EmbeddedBinaryData/JuceLibraryCode/BinaryData11.cpp.o
[ 30%] Building CXX object BinaryResources/CMakeFiles/EmbeddedBinaryData.dir/juce_binarydata_EmbeddedBinaryData/JuceLibraryCode/BinaryData13.cpp.o
[ 30%] Building CXX object BinaryResources/CMakeFiles/EmbeddedBinaryData.dir/juce_binarydata_EmbeddedBinaryData/JuceLibraryCode/BinaryData14.cpp.o
[ 32%] Linking CXX static library libEmbeddedBinaryData.a
[ 32%] Built target EmbeddedBinaryData
make: *** [Makefile:136: all] Error 2
`

**Comment by JanosGit** [comment]
Did you follow the build instructions and installed a rust toolchain? The error indicates that it cannot find `cargo` which is a rust related tool required for the build.

**Comment by buscon** [comment]
> Did you follow the build instructions and installed a rust toolchain? The error indicates that it cannot find `cargo` which is a rust related tool required for the build.

no, I did not do that. Where can I find such build instructions? I cannot see any in the README.md.

**Comment by JanosGit** [comment]
You find a brief build instructions section in the main readme: https://github.com/JanosGit/Schrammel_OJD#how-to-build-the-plugin-from-source

**Comment by buscon** [comment]
ok, got it. now I installed the rust toolchain and it works. Thanks!

**Comment by JanosGit** [comment]
Glad you got it working 🙂
