### ISSUE TITLE
Windows installer: Remove ability to chose the base directory

### ISSUE THREAD

**Issue by JanosGit** [JanosGit/Schrammel_OJD#9]
As VST3 has a fixed install location, this dialog confuses people 
![](https://www.gearslutz.com/board/attachments/new-product-alert/927533d1605792512-free-amp-open-source-overdrive-vst-au-ojd1.jpg)

Reported on [gearslutz.com](https://www.gearslutz.com/board/new-product-alert/1332352-free-amp-open-source-overdrive-vst-au.html). Will be fixed with the next release

**Comment by klinge** [comment]
Just a comment on this: if I recall correctly the installer just puts some un-installer data in this directory  right now. So at this stage I think removing the dialog would be ok. 

But if you ever plan on writing other application data to this folder I think it is great to have a choice on where to install the application (I'm running a not-so-big ssd disk as my c: so I always dislike applications that installs on c: without me being able to select where to install them). 

It's fairly common for VST-plugin installers that users have so select a folder for the application files themselves, another folder for the VST2  (if there is a VST2) and then have the VST3 installed to the default location..
